# Generated by Django 4.2.23 on 2026-01-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspelers',
        ),
    ]
